export const RESERVED_USERNAMES = new Set([
    // core
    "admin",
    "administrator",
    "root",
    "system",
    "owner",
    "founder",
    "team",
    "staff",
    "support",
    "help",
    "contact",
    "legal",
    "security",
    "moderator",
    "mod",
  
    // auth
    "login",
    "log-in",
    "signin",
    "sign-in",
    "signup",
    "sign-up",
    "register",
    "registration",
    "logout",
    "log-out",
    "auth",
    "password",
    "reset",
    "verify",
    "verification",
    "confirmed",
    "confirmation",
  
    // user/account
    "account",
    "accounts",
    "profile",
    "profiles",
    "settings",
    "preferences",
    "me",
    "myself",
    "user",
    "users",
    "usuario",
    "usuarios",
    "perfil",
    "perfiles",
    "cuenta",
    "cuentas",
    "configuracion",
    "ajustes",
    "configuracoes",
    "conta",
  
    // app sections
    "home",
    "inicio",
    "start",
    "welcome",
    "explore",
    "discover",
    "feed",
    "news",
    "updates",
    "search",
    "buscar",
    "busqueda",
    "pesquisa",
    "explorar",
  
    // courses/content
    "course",
    "courses",
    "curso",
    "cursos",
    "class",
    "classes",
    "lesson",
    "lessons",
    "library",
    "content",
    "contenido",
    "biblioteca",
    "resources",
    "recursos",
    "material",
    "materials",
  
    // business/platform
    "app",
    "platform",
    "plataforma",
    "sistema",
    "workspace",
    "portal",
    "product",
    "produto",
    "products",
    "produtos",
  
    // community
    "community",
    "comunidad",
    "comunidade",
    "forum",
    "foro",
    "groups",
    "group",
    "grupos",
    "grupo",
    "network",
    "red",
    "rede",
  
    // private areas
    "dashboard",
    "panel",
    "adminpanel",
    "console",
    "studio",
    "backoffice",
    "office",
  
    // payments
    "billing",
    "payment",
    "payments",
    "checkout",
    "subscription",
    "subscriptions",
    "plan",
    "plans",
    "pricing",
    "pago",
    "pagos",
    "suscripcion",
    "suscripciones",
    "precio",
    "precios",
    "assinatura",
    "assinaturas",
    "pagamento",
    "pagamentos",
    "planos",
  
    // legal/system paths
    "api",
    "apis",
    "webhook",
    "webhooks",
    "internal",
    "private",
    "public",
    "static",
    "assets",
    "cdn",
    "terms",
    "privacy",
    "cookies",
    "policy",
    "policies",
    "terminos",
    "privacidad",
    "politica",
    "politicas",
    "termos",
    "privacidade",
  
    // generic routes
    "new",
    "edit",
    "create",
    "delete",
    "update",
    "view",
    "open",
    "close",
    "send",
    "share",
  
    // short technical
    "u",
    "id",
    "www",
    "mail",
    "email",
    "sms",
    "ftp",
    "http",
    "https",
  
    // brand protection
    "use",
    "unifiedselfevolution",
    "templanza",
    "empowerapp",
    "centrotemplanza",
  
    // spanish
    "iniciar",
    "ingresar",
    "entrar",
    "salir",
    "registrarse",
    "registro",
    "inicio-sesion",
    "mi-cuenta",
    "mi-perfil",
    "mis-cursos",
    "mis-certificados",
    "certificado",
    "certificados",
    "tablero",
    "inicio-app",
  
    // english
    "my-account",
    "my-profile",
    "my-courses",
    "my-certificates",
    "certificate",
    "certificates",
    "get-started",
  
    // portuguese
    "entrar",
    "registrar",
    "cadastro",
    "sair",
    "perfil-publico",
    "meus-cursos",
    "meus-certificados",
    "certificado",
    "certificados",
  ]);